# Generated by Django 4.0.3 on 2022-03-20 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YesNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='disabled',
        ),
        migrations.AddField(
            model_name='member',
            name='disability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.yesno'),
        ),
    ]
